/* Manga source adapters return one normalized shape. Add a connector with
   matches(url) and scan(url); UI and storage remain source-independent. */
const STORAGE_KEY = 'manga-reader-library-v1';
const OFFLINE_DB = 'manga-reader-offline-v1';
let offlineDbPromise;
function getOfflineDb(){if(!('indexedDB'in window))return Promise.reject(Error('Le stockage hors ligne n’est pas disponible dans ce navigateur.'));if(offlineDbPromise)return offlineDbPromise;offlineDbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(OFFLINE_DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('images')){const store=db.createObjectStore('images',{keyPath:'key'});store.createIndex('byDownload','downloadKey',{unique:false})}if(!db.objectStoreNames.contains('downloads'))db.createObjectStore('downloads',{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||Error('Impossible d’ouvrir le stockage hors ligne.'))});return offlineDbPromise}
function offlineRequest(storeName,mode,action){return getOfflineDb().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction(storeName,mode),store=tx.objectStore(storeName);let request;try{request=action(store)}catch(error){reject(error);return}request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||Error('Échec du stockage local.'));tx.onabort=()=>reject(tx.error||Error('Échec du stockage local.'))}))}
function offlineKey(manga,chapter){return `${manga.id||manga.sourceUrl}::${chapter.id||chapter.number}`}
function getOfflineImage(key,page){return offlineRequest('images','readonly',store=>store.get(`${key}|${page}`)).then(record=>record?.blob||null)}
function getOfflineMetadata(manga){const prefix=`${manga.id||manga.sourceUrl}::`;return offlineRequest('downloads','readonly',store=>store.getAll()).then(records=>records.filter(record=>record.key.startsWith(prefix)))}
function saveOfflineImage(key,page,blob){return offlineRequest('images','readwrite',store=>store.put({key:`${key}|${page}`,downloadKey:key,page,blob}))}
function saveOfflineMetadata(record){return offlineRequest('downloads','readwrite',store=>store.put(record))}
function deleteOfflineMetadata(key){return offlineRequest('downloads','readwrite',store=>store.delete(key))}
function deleteOfflineImages(key){return getOfflineDb().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction('images','readwrite'),store=tx.objectStore('images'),index=store.index('byDownload'),cursor=index.openKeyCursor(IDBKeyRange.only(key));cursor.onsuccess=()=>{const item=cursor.result;if(item){store.delete(item.primaryKey);item.continue()}};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||Error('Impossible de libérer le stockage local.'))}))}
const starterManga = [
  {id:'blue-lock',title:'Blue Lock',alternativeTitles:[],author:'Muneyuki Kaneshiro',genres:['Sport','Action'],description:'Après la défaite du Japon en Coupe du monde, trois cents attaquants sont réunis dans un centre d’entraînement hors norme.',cover:'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=500&q=85',source:'Collection personnelle',sourceUrl:'',addedAt:'2025-09-14',lastScannedAt:'2025-10-08',chapters:[{number:286,title:'La pièce manquante',readStatus:'unread'},{number:285,title:'Le dernier duel',readStatus:'read'},{number:284,title:'Nouveau départ',readStatus:'read'},{number:283,title:'Une autre vision',readStatus:'read'}]},
  {id:'dandadan',title:'Dandadan',alternativeTitles:[],author:'Yukinobu Tatsu',genres:['Action','Surnaturel'],description:'Momo et Okarun partent à la rencontre des fantômes et des extraterrestres.',cover:'https://images.unsplash.com/photo-1614583225154-5fcafb41f2ad?auto=format&fit=crop&w=500&q=85',source:'Collection personnelle',sourceUrl:'',addedAt:'2025-08-21',lastScannedAt:'2025-10-06',chapters:[{number:167,title:'L’appel',readStatus:'unread'},{number:166,title:'Tout recommence',readStatus:'read'},{number:165,title:'Le visiteur',readStatus:'read'}]},
  {id:'chainsaw-man',title:'Chainsaw Man',alternativeTitles:[],author:'Tatsuki Fujimoto',genres:['Action','Surnaturel'],description:'Denji, un jeune homme acculé par les dettes, devient Chainsaw Man.',cover:'https://images.unsplash.com/photo-1601850494422-3cf14624b0b3?auto=format&fit=crop&w=500&q=85',source:'Collection personnelle',sourceUrl:'',addedAt:'2025-06-03',lastScannedAt:'2025-10-04',chapters:[{number:218,title:'Rêve ou réalité',readStatus:'unread'},{number:217,title:'La ville',readStatus:'unread'},{number:216,title:'Sans détour',readStatus:'read'}]},
  {id:'frieren',title:'Frieren',alternativeTitles:['Sousou no Frieren'],author:'Kanehito Yamada',genres:['Aventure','Fantaisie'],description:'Après la victoire du groupe du héros, l’elfe Frieren entame un nouveau voyage.',cover:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=500&q=85',source:'Collection personnelle',sourceUrl:'',addedAt:'2025-04-19',lastScannedAt:'2025-10-01',chapters:[{number:140,title:'Le long chemin',readStatus:'unread'},{number:139,title:'Le ciel lointain',readStatus:'read'}]}
];
const palette=['#c6734d','#4b7473','#b18454','#6f6791','#a15c67','#527396'];
function loadLibrary(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(v)?v:starterManga}catch{return starterManga}}
let library=loadLibrary(), activeFilter='all', query='';
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(library))}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pct(m){const total=m.chapters?.length||0,read=m.chapters?.filter(c=>c.readStatus==='read').length||0;return total?Math.round(read/total*100):0}
function render(){const grid=document.querySelector('#manga-grid'),sort=document.querySelector('#sort-select').value;let items=[...library];if(query){const q=query.toLocaleLowerCase('fr');items=items.filter(m=>[m.title,m.author,...(m.genres||[]),...(m.alternativeTitles||[]),...(m.chapters||[]).map(c=>c.title)].join(' ').toLocaleLowerCase('fr').includes(q))}if(activeFilter==='reading')items=items.filter(m=>pct(m)>0&&pct(m)<100);if(activeFilter==='unread')items=items.filter(m=>pct(m)===0);if(activeFilter==='complete')items=items.filter(m=>pct(m)===100);if(activeFilter==='favorites')items=items.filter(m=>m.favorite);items.sort(sort==='title'?(a,b)=>a.title.localeCompare(b.title,'fr'):sort==='chapters'?(a,b)=>(b.chapters?.length||0)-(a.chapters?.length||0):sort==='progress'?(a,b)=>pct(b)-pct(a):(a,b)=>String(b.addedAt).localeCompare(String(a.addedAt)));document.querySelector('#nav-count').textContent=library.length;document.querySelector('#library-count').textContent=String(library.length).padStart(2,'0');document.querySelector('#filter-all').textContent=library.length;grid.innerHTML=items.map((m,i)=>{const total=m.chapters?.length||0,last=m.chapters?.[0];return `<article class="manga-card" data-id="${escapeHtml(m.id)}"><div class="cover" style="--cover:${palette[i%palette.length]}">${m.cover?`<img src="${escapeHtml(m.cover)}" alt="Couverture de ${escapeHtml(m.title)}" loading="lazy" onerror="this.remove()">`:''}<span class="cover-fallback">${escapeHtml(m.title.slice(0,1))}</span><button class="favorite ${m.favorite?'is-fav':''}" aria-label="${m.favorite?'Retirer des favoris':'Ajouter aux favoris'}" data-action="favorite">♥</button><span class="cover-source">${escapeHtml(m.source||'Source')}</span></div><div class="card-content"><div class="card-meta"><span>${escapeHtml(m.author||'Auteur inconnu')}</span><span class="genre-dot">·</span><span>${escapeHtml(m.genres?.[0]||'Manga')}</span></div><h3>${escapeHtml(m.title)}</h3><div class="chapter-line"><span>CHAPITRE <b>${escapeHtml(last?.number??'—')}</b></span><span>${total} chapitres</span></div><div class="progress-track"><i style="width:${pct(m)}%"></i></div><div class="progress-label"><span>${pct(m)} % lu</span><button data-action="chapters">Chapitres <b>→</b></button></div><div class="card-foot"><span>Dernier scan</span><time>${escapeHtml(m.lastScannedAt||'Non scanné')}</time></div></div></article>`}).join('');document.querySelector('#empty-state').hidden=items.length>0;grid.hidden=items.length===0}
function message(text,type=''){const el=document.querySelector('#scan-status');el.textContent=text;el.className=`scan-status ${type}`}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function isAndroidNative(){return window.Capacitor?.getPlatform?.()==='android'}

class SourceAdapter{matches(_url){return false}async scan(_url){throw new Error('Connecteur non configuré')}}
async function fetchConnector(url,endpoint='/api/page',label='la fiche'){
  try{const response=await fetch(isAndroidNative()?url:`${endpoint}?url=${encodeURIComponent(url)}`,{signal:AbortSignal.timeout(20000)});if(isAndroidNative()){if(!response.ok)throw Error(response.status===404?'Cette fiche manga est introuvable (404).':`Le site a répondu avec l’erreur ${response.status}.`);return endpoint==='/api/data'?{data:await response.json()}:{html:await response.text()}}const result=await response.json();if(!response.ok)throw new Error(result.error||'Impossible de charger cette page.');return result}catch(e){if(e.name==='TimeoutError')throw new Error(`Le site n’a pas répondu en 20 secondes pendant le chargement de ${label}.`);if(e instanceof TypeError&&!isAndroidNative())throw new Error('Le serveur de scan ne répond pas. Lancez l’aperçu avec node server.js.');throw e}
}
async function loadPage(url){const result=await fetchConnector(url),doc=new DOMParser().parseFromString(result.html,'text/html');if(/captcha|cloudflare|just a moment|verify you are human/i.test(doc.title+' '+doc.body?.innerText?.slice(0,600)))throw new Error('Le site présente une protection anti-bot.');return doc}
class AnimeSamaAdapter extends SourceAdapter{
  matches(url){return url.hostname==='anime-sama.to'&&/\/catalogue\/[^/]+\/scan\//i.test(url.pathname)}
  async scan(input){
    const url=new URL(input);
    const doc=await loadPage(url.href),title=doc.querySelector('#titreOeuvre')?.textContent?.trim()||doc.querySelector('meta[property="og:title"]')?.content?.split(' - Scans')[0]||doc.title?.trim();if(!title)throw new Error('Le titre de cette fiche Anime-Sama est introuvable.');
    const dataUrl=new URL('/s2/scans/get_nb_chap_et_img.php',url.origin);dataUrl.searchParams.set('oeuvre',title);const result=await fetchConnector(dataUrl.href,'/api/data','la liste des chapitres');const entries=Object.keys(result.data||{}).filter(k=>/^\d+(?:\.\d+)?$/.test(k));if(!entries.length)throw new Error('Anime-Sama ne renvoie aucun chapitre pour cette fiche.');
    const chapters=entries.sort((a,b)=>Number(b)-Number(a)).map(number=>({id:`${url.origin}${url.pathname}#chapter-${number}`,mangaId:null,number,title:`Chapitre ${number}`,pageCount:Number(result.data[number])||0,url:url.href,source:'Anime-Sama',releaseDate:null,discoveredAt:new Date().toISOString(),readStatus:'unread',favorite:false}));
    return{id:`anime-sama-${url.pathname.split('/')[2]}`,title,alternativeTitles:[],cover:doc.querySelector('meta[property="og:image"]')?.content||'',description:doc.querySelector('meta[name="description"]')?.content||'',author:'',artist:'',status:'',genres:[],source:'Anime-Sama',sourceUrl:url.href,addedAt:new Date().toISOString().slice(0,10),lastScannedAt:new Date().toISOString().slice(0,10),chapters};
  }
}
class GenericPublicPageAdapter extends SourceAdapter{
  matches(_url){return true}
  async scan(url){
    const doc=await loadPage(url.href);
    const title=doc.querySelector('meta[property="og:title"]')?.content||doc.querySelector('h1')?.textContent?.trim()||doc.title?.trim();if(!title)throw new Error('La structure de cette page n’est pas reconnue.');
    const chapterLinks=[...doc.querySelectorAll('a[href]')].filter(a=>/chapter|chapitre|chap\.?\s*\d|episode/i.test(`${a.textContent} ${a.href}`));const seen=new Set(),chapters=[];for(const a of chapterLinks){const href=new URL(a.getAttribute('href'),url).href;if(seen.has(href))continue;seen.add(href);const label=a.textContent.trim().replace(/\s+/g,' '),match=label.match(/(?:chapter|chapitre|chap\.?|ch\.?)[\s#-]*(\d+(?:\.\d+)?)/i)||label.match(/\b(\d+(?:\.\d+)?)\b/);chapters.push({id:href,number:match?.[1]||null,title:label||`Chapitre ${match?.[1]||''}`,url:href,source:new URL(url).hostname,releaseDate:null,discoveredAt:new Date().toISOString(),readStatus:'unread',favorite:false})}if(!chapters.length)throw new Error('Aucun chapitre détecté. Cette source peut nécessiter un connecteur dédié.');
    return {id:`${new URL(url).hostname}-${title}`.toLowerCase().replace(/[^a-z0-9]+/g,'-'),title:title.replace(/\s*[|–-]\s*.+$/,''),alternativeTitles:[],cover:doc.querySelector('meta[property="og:image"]')?.content||'',description:doc.querySelector('meta[name="description"]')?.content||doc.querySelector('meta[property="og:description"]')?.content||'',author:'',artist:'',status:'',genres:[],source:new URL(url).hostname,sourceUrl:url,addedAt:new Date().toISOString().slice(0,10),lastScannedAt:new Date().toISOString().slice(0,10),chapters};
  }
}
const adapters=[new AnimeSamaAdapter(),new GenericPublicPageAdapter()];
let pickerManga=null,activeChapter=null,activeChapterIndex=-1,imageObserver=null,pagesAdded=0,readerControlsTimer=null,lastReaderScrollTop=0,downloadedChapterKeys=new Set(),downloadedMetadata=new Map(),downloadProgress=new Map(),showDownloadedOnly=false,activeChapterDownloaded=false,activeObjectUrls=[];
const readerDialog=document.querySelector('#reader-dialog');
function renderChapterPicker(){if(!pickerManga)return;const q=document.querySelector('#chapter-search').value.trim().toLocaleLowerCase('fr'),list=document.querySelector('#chapter-list'),chapters=pickerManga.chapters||[],downloaded=chapters.filter(c=>downloadedChapterKeys.has(offlineKey(pickerManga,c))).length;document.querySelector('#chapter-total').textContent=showDownloadedOnly?`${downloaded} téléchargés · ${chapters.length} chapitres`:`${chapters.length} chapitres`;document.querySelector('#filter-downloads').classList.toggle('active',showDownloadedOnly);document.querySelector('#filter-downloads').setAttribute('aria-pressed',String(showDownloadedOnly));const filtered=chapters.map((c,i)=>({c,i,key:offlineKey(pickerManga,c)})).filter(({c,key})=>(!showDownloadedOnly||downloadedChapterKeys.has(key))&&(!q||`${c.title} ${c.number}`.toLocaleLowerCase('fr').includes(q)));list.innerHTML=filtered.map(({c,i,key})=>{const marked=c.id===pickerManga.currentChapterId,isDownloaded=downloadedChapterKeys.has(key),progress=downloadProgress.get(key),canDownload=Number(c.pageCount)>0&&pickerManga.source==='Anime-Sama';return `<div class="chapter-entry ${marked?'is-current':''}"><button class="chapter-download ${isDownloaded?'is-downloaded':''}" data-download-index="${i}" aria-label="${isDownloaded?'Téléchargé hors ligne':progress?'Téléchargement en cours':'Télécharger ce chapitre'}" title="${isDownloaded?'Téléchargé hors ligne':progress?'Téléchargement en cours':'Télécharger hors ligne'}" ${isDownloaded||progress||!canDownload?'disabled':''}>${isDownloaded?'✓':progress?`${progress.done}/${progress.total}`:'⇩'}</button><button class="chapter-select" data-chapter-index="${i}" ${canDownload?'':'disabled'}><span class="chapter-entry-number">${escapeHtml(c.title||`Chapitre ${c.number}`)}${marked?'<b class="current-chapter-mark">⚑ EN COURS</b>':''}</span><span class="chapter-entry-info">${c.readStatus==='read'?'LU':'À LIRE'}${c.pageCount?` · ${escapeHtml(c.pageCount)} pages`:''}</span><span class="chapter-entry-arrow">${canDownload?'→':'—'}</span></button></div>`}).join('')||`<p class="chapter-empty">${showDownloadedOnly?'Aucun chapitre téléchargé.':'Aucun chapitre ne correspond à cette recherche.'}</p>`;document.querySelector('#jump-bookmark').disabled=!pickerManga.currentChapterId;document.querySelector('#refresh-chapters').disabled=pickerManga.source!=='Anime-Sama';}
function chooseMangaChapters(manga){pickerManga=manga;activeChapter=null;downloadedChapterKeys=new Set();downloadedMetadata.clear();showDownloadedOnly=false;document.querySelector('#reader-title').textContent=manga.title;document.querySelector('#reader-kicker').textContent=`${manga.source||'SOURCE'} · ${manga.chapters?.length||0} CHAPITRES`;document.querySelector('#reader-back').hidden=true;document.querySelector('#reader-actions').hidden=false;document.querySelector('#chapter-picker-view').hidden=false;document.querySelector('#reader-view').hidden=true;document.querySelector('#chapter-search').value='';renderChapterPicker();readerDialog.showModal();getOfflineMetadata(manga).then(records=>{if(pickerManga!==manga)return;downloadedChapterKeys=new Set(records.map(record=>record.key));downloadedMetadata=new Map(records.map(record=>[record.key,record]));renderChapterPicker()}).catch(()=>{});}
function revokeReaderObjectUrls(){activeObjectUrls.forEach(url=>URL.revokeObjectURL(url));activeObjectUrls=[]}
async function addReaderPages(){if(!activeChapter||pagesAdded>=Number(activeChapter.pageCount))return;const chapter=activeChapter,manga=pickerManga,container=document.querySelector('#reader-pages'),end=Math.min(pagesAdded+3,Number(chapter.pageCount)),start=pagesAdded+1;for(let page=start;page<=end;page++){const img=document.createElement('img');img.alt=`${manga.title} — ${chapter.title}, page ${page}`;img.loading=page===1?'eager':'lazy';img.decoding='async';img.dataset.page=page;try{let source;if(activeChapterDownloaded){const blob=await getOfflineImage(offlineKey(manga,chapter),page);if(blob){source=URL.createObjectURL(blob);activeObjectUrls.push(source)}else if(navigator.onLine)source=null;else throw Error('Cette page téléchargée est introuvable sur l’appareil.')}if(activeChapter!==chapter)return;if(!source){const remote=new URL(`/s2/scans/${encodeURIComponent(manga.title)}/${encodeURIComponent(chapter.number)}/${page}.jpg`,new URL(manga.sourceUrl).origin);source=isAndroidNative()?remote.href:`/api/image?url=${encodeURIComponent(remote.href)}`}img.src=source}catch(error){img.classList.add('image-error');img.alt=error.message;if(activeChapter===chapter)document.querySelector('#reader-load-status').textContent=error.message}img.onload=()=>{if(img.src.startsWith('blob:')){URL.revokeObjectURL(img.src);activeObjectUrls=activeObjectUrls.filter(url=>url!==img.src)}if(activeChapter===chapter&&page===1&&chapter.readStatus!=='read'){chapter.readStatus='read';save();render()}if(activeChapter===chapter)document.querySelector('#reader-load-status').textContent=`${activeChapterDownloaded?'Hors ligne · ':''}Page ${page} chargée sur ${chapter.pageCount}`};img.onerror=()=>{if(img.src.startsWith('blob:')){URL.revokeObjectURL(img.src);activeObjectUrls=activeObjectUrls.filter(url=>url!==img.src)}if(activeChapter!==chapter)return;img.classList.add('image-error');img.alt=`Page ${page} indisponible pour ce chapitre`;document.querySelector('#reader-load-status').textContent=`La page ${page} n’a pas pu être chargée.`};container.append(img)}if(activeChapter!==chapter)return;pagesAdded=end;const sentinel=document.createElement('div');sentinel.className='reader-sentinel';sentinel.setAttribute('aria-hidden','true');container.append(sentinel);if(imageObserver)imageObserver.disconnect();imageObserver=new IntersectionObserver(entries=>{if(entries.some(x=>x.isIntersecting)){imageObserver.disconnect();sentinel.remove();addReaderPages()}},{root:container,rootMargin:'700px 0px'});imageObserver.observe(sentinel);document.querySelector('#reader-page-label').textContent=`${chapter.title} · ${chapter.pageCount} pages${activeChapterDownloaded?' · HORS LIGNE':''}`;document.querySelector('#reader-older').disabled=activeChapterIndex>=manga.chapters.length-1;document.querySelector('#reader-newer').disabled=activeChapterIndex<=0;}
function clearReaderControlsTimer(){if(readerControlsTimer){clearTimeout(readerControlsTimer);readerControlsTimer=null}}
function scheduleReaderControlsHide(){clearReaderControlsTimer();readerControlsTimer=setTimeout(()=>readerDialog.classList.add('reader-controls-hidden'),3000)}
function exitReaderFullscreen(){clearReaderControlsTimer();readerDialog.classList.remove('reader-fullscreen-mode','reader-controls-hidden','reader-fullscreen-fallback');if(document.fullscreenElement===readerDialog&&document.exitFullscreen)document.exitFullscreen().catch(()=>{});const button=document.querySelector('#reader-fullscreen');button.setAttribute('aria-label','Passer en plein écran');button.title='Plein écran'}
async function toggleReaderFullscreen(){if(document.fullscreenElement===readerDialog||readerDialog.classList.contains('reader-fullscreen-fallback')){exitReaderFullscreen();return}try{if(!readerDialog.requestFullscreen)throw Error('API plein écran indisponible');await readerDialog.requestFullscreen();readerDialog.classList.remove('reader-fullscreen-fallback')}catch{readerDialog.classList.add('reader-fullscreen-fallback')}readerDialog.classList.add('reader-fullscreen-mode','reader-controls-hidden');clearReaderControlsTimer();document.querySelector('#reader-fullscreen').setAttribute('aria-label','Quitter le plein écran');document.querySelector('#reader-fullscreen').title='Quitter le plein écran'}
function returnToChapterList(){exitReaderFullscreen();revokeReaderObjectUrls();if(imageObserver)imageObserver.disconnect();activeChapter=null;activeChapterDownloaded=false;document.querySelector('#reader-view').hidden=true;document.querySelector('#chapter-picker-view').hidden=false;document.querySelector('#reader-back').hidden=true;document.querySelector('#reader-fullscreen').hidden=true;document.querySelector('#reader-actions').hidden=false;renderChapterPicker()}
function onReaderScroll(){const pages=document.querySelector('#reader-pages'),position=pages.scrollTop,goingUp=position<lastReaderScrollTop-6;lastReaderScrollTop=position;if(!readerDialog.classList.contains('reader-fullscreen-mode')||!goingUp)return;readerDialog.classList.remove('reader-controls-hidden');scheduleReaderControlsHide()}
function openReaderChapter(index){if(!pickerManga||pickerManga.source!=='Anime-Sama'){toast('Le lecteur intégré est disponible pour Anime-Sama.');return}activeChapterIndex=index;activeChapter=pickerManga.chapters[index];if(!Number(activeChapter?.pageCount)){toast('Aucune page accessible pour ce chapitre.');return}revokeReaderObjectUrls();activeChapterDownloaded=downloadedChapterKeys.has(offlineKey(pickerManga,activeChapter));pickerManga.currentChapterId=activeChapter.id;save();document.querySelector('#chapter-picker-view').hidden=true;document.querySelector('#reader-view').hidden=false;document.querySelector('#reader-back').hidden=false;document.querySelector('#reader-actions').hidden=true;document.querySelector('#reader-fullscreen').hidden=false;document.querySelector('#reader-title').textContent=activeChapter.title;document.querySelector('#reader-kicker').textContent=pickerManga.title;const pages=document.querySelector('#reader-pages');pages.innerHTML='';pages.scrollTop=0;lastReaderScrollTop=0;document.querySelector('#reader-load-status').textContent=activeChapterDownloaded?'Ouverture du chapitre hors ligne…':'Chargement des premières pages…';pagesAdded=0;if(imageObserver)imageObserver.disconnect();addReaderPages();}
async function downloadChapter(index,button){const chapter=pickerManga?.chapters[index],manga=pickerManga;if(!manga||!chapter)return;const key=offlineKey(manga,chapter);if(downloadedChapterKeys.has(key)||downloadProgress.has(key))return;const total=Number(chapter.pageCount)||0;if(!total){toast('Ce chapitre ne contient pas de pages téléchargeables.');return}if(!navigator.onLine){toast('Connectez-vous pour télécharger ce chapitre.');return}downloadProgress.set(key,{done:0,total});renderChapterPicker();toast(`Téléchargement de ${chapter.title}…`);let bytes=0;try{for(let page=1;page<=total;page++){const remote=new URL(`/s2/scans/${encodeURIComponent(manga.title)}/${encodeURIComponent(chapter.number)}/${page}.jpg`,new URL(manga.sourceUrl).origin),requestUrl=isAndroidNative()?remote.href:`/api/image?url=${encodeURIComponent(remote.href)}`,response=await fetch(requestUrl,{signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error(`La page ${page} n’a pas pu être téléchargée.`);const blob=await response.blob();if(!blob.type.startsWith('image/'))throw Error(`La page ${page} reçue n’est pas une image.`);await saveOfflineImage(key,page,blob);bytes+=blob.size;downloadProgress.set(key,{done:page,total});const progressButton=document.querySelector(`[data-download-index="${index}"]`);if(progressButton)progressButton.textContent=`${page}/${total}`}const record={key,mangaId:manga.id,chapterId:chapter.id,chapterTitle:chapter.title,pageCount:total,bytes,savedAt:new Date().toISOString()};await saveOfflineMetadata(record);downloadedChapterKeys.add(key);downloadedMetadata.set(key,record);toast(`${chapter.title} disponible hors ligne.`)}catch(error){try{await deleteOfflineImages(key);await deleteOfflineMetadata(key)}catch{}downloadedChapterKeys.delete(key);downloadedMetadata.delete(key);const reason=/quota|storage|disk/i.test(`${error.name} ${error.message}`)?'Stockage insuffisant sur cet appareil.':error.message||'Le téléchargement a échoué.';toast(reason)}finally{downloadProgress.delete(key);if(pickerManga===manga)renderChapterPicker()}}
document.querySelector('#chapter-search').addEventListener('input',renderChapterPicker);document.querySelector('#chapter-list').addEventListener('click',e=>{const downloadButton=e.target.closest('[data-download-index]');if(downloadButton){e.preventDefault();e.stopPropagation();downloadChapter(Number(downloadButton.dataset.downloadIndex),downloadButton);return}const row=e.target.closest('[data-chapter-index]');if(row&&!row.disabled)openReaderChapter(Number(row.dataset.chapterIndex))});document.querySelector('#filter-downloads').addEventListener('click',e=>{showDownloadedOnly=!showDownloadedOnly;e.currentTarget.setAttribute('aria-pressed',String(showDownloadedOnly));renderChapterPicker()});document.querySelector('#reader-back').addEventListener('click',returnToChapterList);document.querySelector('#reader-close').addEventListener('click',()=>{if(!document.querySelector('#reader-view').hidden)returnToChapterList();else readerDialog.close()});readerDialog.addEventListener('close',()=>{exitReaderFullscreen();revokeReaderObjectUrls();if(imageObserver)imageObserver.disconnect();activeChapter=null});document.querySelector('#reader-older').addEventListener('click',()=>openReaderChapter(activeChapterIndex+1));document.querySelector('#reader-newer').addEventListener('click',()=>openReaderChapter(activeChapterIndex-1));document.querySelector('#reader-fullscreen').addEventListener('click',toggleReaderFullscreen);document.querySelector('#reader-pages').addEventListener('scroll',onReaderScroll,{passive:true});document.addEventListener('fullscreenchange',()=>{if(document.fullscreenElement===readerDialog){readerDialog.classList.add('reader-fullscreen-mode','reader-controls-hidden');clearReaderControlsTimer()}else if(!readerDialog.classList.contains('reader-fullscreen-fallback')){readerDialog.classList.remove('reader-fullscreen-mode','reader-controls-hidden');clearReaderControlsTimer();document.querySelector('#reader-fullscreen').setAttribute('aria-label','Passer en plein écran');document.querySelector('#reader-fullscreen').title='Plein écran'}});
document.querySelector('#jump-bookmark').addEventListener('click',()=>{if(!pickerManga?.currentChapterId){toast('Aucun chapitre de reprise enregistré.');return}const index=pickerManga.chapters.findIndex(c=>c.id===pickerManga.currentChapterId);if(index<0){toast('Le chapitre marqué ne figure plus dans la liste.');return}showDownloadedOnly=false;document.querySelector('#chapter-search').value='';renderChapterPicker();const row=document.querySelector(`[data-chapter-index="${index}"]`);row?.scrollIntoView({behavior:'smooth',block:'center'});row?.classList.add('mark-highlight');setTimeout(()=>row?.classList.remove('mark-highlight'),1600)});
document.querySelector('#refresh-chapters').addEventListener('click',async e=>{const button=e.currentTarget;if(!pickerManga||pickerManga.source!=='Anime-Sama')return;button.disabled=true;button.classList.add('is-refreshing');document.querySelector('#chapter-total').textContent='Actualisation…';try{const adapter=adapters.find(a=>a.matches(new URL(pickerManga.sourceUrl)));const updated=await adapter.scan(pickerManga.sourceUrl),oldById=new Map(pickerManga.chapters.map(c=>[c.id||c.url,c])),newIds=new Set(updated.chapters.map(c=>c.id||c.url)),added=updated.chapters.filter(c=>!oldById.has(c.id||c.url));pickerManga.chapters=[...updated.chapters.map(c=>{const old=oldById.get(c.id||c.url);return old?{...old,...c,readStatus:old.readStatus||c.readStatus,favorite:old.favorite||c.favorite}:c}),...pickerManga.chapters.filter(c=>!newIds.has(c.id||c.url))];pickerManga.lastScannedAt=updated.lastScannedAt;pickerManga.cover=updated.cover||pickerManga.cover;save();renderChapterPicker();render();toast(added.length?`${added.length} nouveau${added.length>1?'x':''} chapitre${added.length>1?'s':''} ajouté${added.length>1?'s':''}.`:'Liste des chapitres à jour.')}catch(err){document.querySelector('#chapter-total').textContent=`${pickerManga.chapters.length} chapitres`;toast(err.message||'Actualisation impossible.')}finally{button.disabled=false;button.classList.remove('is-refreshing')}});
document.querySelector('#scan-form').addEventListener('submit',async e=>{e.preventDefault();const input=document.querySelector('#manga-url'),button=e.currentTarget.querySelector('button[type=submit]');let url;try{url=new URL(input.value.trim());if(!['http:','https:'].includes(url.protocol))throw 0}catch{message('Saisissez une adresse web valide commençant par https://.','error');input.focus();return}const adapter=adapters.find(a=>a.matches(url));button.disabled=true;button.innerHTML='<span>Analyse en cours…</span><span class="spinner"></span>';message('Chargement de la fiche et recherche des chapitres…','loading');try{const result=await adapter.scan(url.href),old=library.find(m=>m.sourceUrl===result.sourceUrl||m.id===result.id);if(old){const oldById=new Map(old.chapters.map(c=>[c.id||c.url,c])),newIds=new Set(result.chapters.map(c=>c.id||c.url)),added=result.chapters.filter(c=>!oldById.has(c.id||c.url));old.chapters=[...result.chapters.map(c=>{const previous=oldById.get(c.id||c.url);return previous?{...previous,...c,readStatus:previous.readStatus||c.readStatus,favorite:previous.favorite||c.favorite}:c}),...old.chapters.filter(c=>!newIds.has(c.id||c.url))];old.lastScannedAt=result.lastScannedAt;old.cover=result.cover||old.cover;old.description=result.description||old.description;message(`${result.title} mis à jour · ${added.length} nouveau${added.length>1?'x':''} chapitre${added.length>1?'s':''} détecté${added.length>1?'s':''}.`,'success')}else{library.unshift(result);message(`${result.title} ajouté à votre bibliothèque · ${result.chapters.length} chapitres trouvés.`,'success')}save();render();document.querySelector('#manga-url').value=''}catch(err){message(err.message||'Une erreur inattendue est survenue pendant le scan.','error')}finally{button.disabled=false;button.innerHTML='<span>Scanner</span><span>→</span>'}});
document.querySelector('#paste-url').addEventListener('click',async()=>{try{document.querySelector('#manga-url').value=await navigator.clipboard.readText();toast('Adresse collée')}catch{toast('Autorisez l’accès au presse-papiers dans votre navigateur')}});
document.querySelector('#search-input').addEventListener('input',e=>{query=e.target.value;render()});document.querySelector('#sort-select').addEventListener('change',render);document.querySelector('#filters').addEventListener('click',e=>{const btn=e.target.closest('[data-filter]');if(!btn)return;activeFilter=btn.dataset.filter;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===btn));render()});document.querySelector('#manga-grid').addEventListener('click',e=>{const action=e.target.closest('[data-action]'),card=e.target.closest('.manga-card');if(!action||!card)return;const m=library.find(x=>x.id===card.dataset.id);if(action.dataset.action==='favorite'){m.favorite=!m.favorite;save();render()}if(action.dataset.action==='chapters')chooseMangaChapters(m)});
document.querySelector('#theme-toggle').addEventListener('click',()=>document.body.classList.toggle('light'));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('#search-input').focus()}});document.querySelectorAll('.nav-item').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));a.classList.add('active');document.querySelector('#crumb').textContent=a.textContent.trim().toLocaleUpperCase('fr')}));
render();
if('serviceWorker'in navigator&&!isAndroidNative())navigator.serviceWorker.register('/sw.js').catch(()=>{});
